### ISSUE TITLE
could not load extension icon

### ISSUE THREAD

**Issue by KenanY** [lxe/require-navigator#19]
Just received this error trying to install `0.2.1`:

![2015-04-30-11-16-14-8034947](https://cloud.githubusercontent.com/assets/733364/7416019/86525bbc-ef2a-11e4-8bc7-66253e4aeb76.png)

**Comment by KenanY** [comment]
Hmm installing from `require-navigator.crx` works.

**Comment by lxe** [comment]
Fixing this...

**Comment by lxe** [comment]
Should appear in chrome store in a bit.
